{
  "concurrent": false,
  "linters": {
    "*.{ts,scss,json}, !package.json": ["prettier --write"],
    "*.{ts,json}, !package.json": ["tslint"],
    "*.scss": ["sasslint"],
    "*": ["git add"]
  }
}
