{
  "concurrent": false,
  "linters": {
    "{src,test}/**/*.{ts,scss,json}": ["prettier --write"],
    "{src,test}/**/*.ts": ["tslint"],
    "src/**/*.scss": ["sasslint"],
    "*": ["git add"]
  }
}
